services:
  3dfilamentmanagement:
    build: .
    image: pixelpulse01/3dfilamentmanagement:v0.6.0.0
    container_name: 3dfilamentmanagement
    restart: unless-stopped

    environment:
      - TZ=Asia/Shanghai
      - SECRET_KEY=change-me-to-random-string
      - DATA_DIR=/data

    ports:
      - "9055:3155"

    volumes:
      - /opt/docker-stacks/3D-Consumables-Inventory-Management-System:/data
